//! WEB_TEX — the browser corpus's replacement for the bindless `texs[]`
//! (F2 of the WASM/WebGPU port). WebGPU has no texture arrays of any kind:
//! no unbounded descriptor range, no `NonUniformResourceIndex`, and naga
//! refuses the `ShaderNonUniform` capability outright (the last four
//! `--check-wgsl` failures, measured 2026-08-18). Three mechanisms replace
//! the three things `texs[]` was used for:
//!
//! 1. **A meta side-table** (`web_tex_meta`, t10 space1 — the register the
//!    bindless decl vacates) answers every `GetDimensions` bit-exactly and
//!    carries the bucket remap + texel-payload offset.
//! 2. **A mip-0 texel buffer** (`web_texels`, t11) answers the `.Load`-only
//!    alpha paths (cutout + heightfield). Byte-exact by construction: the
//!    RGBA8 word's top byte IS the alpha byte, so `(word >> 24) < 128` ≡
//!    the native `.a * 255.0 < 127.5` (UNORM n/255 round-trips every byte
//!    exactly in f32 — the alpha_cutout precedent), and `float(word >> 24)`
//!    is exactly the byte the native arm recovers for the height bilinear.
//!    Only cutout/height textures carry a payload (`mat_cutout` ∪
//!    `mat_height` sources — the same derivations the native tables bind).
//! 3. **Exact-size `Texture2DArray` buckets** (t12..) for the sampled path:
//!    textures grouped by (w, h, mip levels, srgb) — no resample, no
//!    padding, every layer is the texture's own bytes — dispatched by a
//!    generated switch on the meta word's bucket half. `bl = bucket << 16 |
//!    layer`.
//!
//! The PLAN half (`plan`) is backend-free data: the native FR_WEB_TEX arm,
//! the wgpu backend and `--bake-web` all consume the same buckets/meta/
//! payload. The CODEGEN half (`hlsl`) emits the declarations + dispatch
//! helpers pasted ahead of the trace units by the web assembler (the
//! spp_defs precedent: generated by shaders.rs-adjacent code, never written
//! by hand at the consumer). Samplers are passed INTO the helpers as
//! parameters — the block is pasted before trace_common.hlsli, where
//! `samp_lin`/`samp_aniso` are declared, and DXC inlines everything anyway.
//!
//! Determinism: bucket order is the BTreeMap order of (w, h, levels, srgb)
//! and layers ascend by texture index, so the plan — and therefore the
//! generated HLSL, the bake output and the W7 corpus golden — is a pure
//! function of the scene.
//!
//! HONEST LIMIT (the W5 audit's subject): one bucket = one WebGPU sampled-
//! texture binding, and the DEFAULT WebGPU limit is 16 per stage. Texture-
//! heavy scenes will need a raised `maxSampledTexturesPerShaderStage` from
//! the adapter (desktop adapters grant far more); the escape hatch, if a
//! floor adapter ever matters, is merging size classes by resample — a
//! quality trade this plan deliberately does not take.
//!
//! **The native FR_WEB_TEX arm** (`FR_WEB_TEX=1`, gpu/trace.rs) binds this
//! plan on native D3D12: `WebTexGpu` uploads the buckets (always RGBA8 — an
//! array resource is ONE format and `should_compress` varies within a bucket
//! key, so BC7 is structurally unreachable; an armed BC7 session's nine trace
//! units simply sample uncompressed buckets while feed/DXR keep the BC7
//! `texs[]`), the generated block is PREPENDED to the browser corpus's nine
//! trace units at the `TraceGpu::new` compile seam (the `web_units` shape —
//! LOCKSTEP with main.rs's `webt` list), and the root signature carries a
//! static space1 range at `META_REG..` sized `trace::WEB_TEX_SLOTS` (a scene
//! over `WEB_TEX_MAX_BUCKETS` falls back to bindless with one loud line).
//! `--check-gpu`'s M15 proves the armed arm against bindless over one
//! `Bc7Mode::Off` core — EXACT on tbuf/info/counters (geometry + the
//! byte-exact Load paths) and on the uploaded bytes (a per-(texture, mip)
//! resource audit), ULP-BOUNDED on accum, which crosses two DXC compilations
//! (measured on bistro/NVIDIA: 43 of 1.44M channels at 1–8 ulp, one screen
//! region, independent of aniso and mips, audit clean — recompiled fusing,
//! the FR_NOPRECISE class) — and bites both meta-row poisons. M15b repeats
//! the comparison on the session scene.
//!
//! Touch this module, the WEB_TEX choke points, or the native arm → run
//! `cargo test`, `--check` (this self_test + the goldens), `--check-wgsl`,
//! `--check-gpu` (M15 fires on every scene; M15b needs a textured one — run
//! bistro AND san-miguel), and `cargo check --target wasm32-unknown-unknown`.

use crate::scene::Scene;
use std::collections::BTreeMap;

/// The space1 registers the generated block declares — the ONE source of
/// truth. `hlsl()` formats its declarations from these, and the native
/// FR_WEB_TEX arm's root-signature range reads them (gpu/trace.rs carries a
/// const assert that the buffer-SRV range ends exactly at `META_REG`).
/// t10/t11 are the registers the bindless decl vacated (see the module note).
pub const META_REG: u32 = 10;
pub const TEXELS_REG: u32 = 11;
pub const BUCKET_REG0: u32 = 12;

/// One `Texture2DArray` bucket: every texture sharing (w, h, levels, srgb).
#[derive(Debug, PartialEq, Eq)]
pub struct Bucket {
    pub w: u32,
    pub h: u32,
    /// Full level count INCLUDING the base (1 = no mips).
    pub levels: u32,
    pub srgb: bool,
    /// Scene texture indices, ascending — the layer order.
    pub layers: Vec<u32>,
}

/// One texture's row in `web_tex_meta` (16 B, index-aligned with
/// `Scene::textures`). `bl` = bucket << 16 | layer; `ofs` indexes
/// `web_texels` or `NO_PAYLOAD`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MetaRow {
    pub w: u32,
    pub h: u32,
    pub bl: u32,
    pub ofs: u32,
}

pub const NO_PAYLOAD: u32 = 0xffff_ffff;

#[derive(Debug, Default)]
pub struct WebTexPlan {
    pub buckets: Vec<Bucket>,
    pub meta: Vec<MetaRow>,
    /// Mip-0 RGBA8 words (r | g<<8 | b<<16 | a<<24 — the BC7_READ pack
    /// convention) for every texture some material's cutout or heightfield
    /// path can `.Load`.
    pub texels: Vec<u32>,
}

/// Group the scene's textures into buckets and lay out the Load-path
/// payload. Pure and deterministic — see the module note.
pub fn plan(scene: &Scene) -> WebTexPlan {
    // The exact Load-path set: the same nonzero sets the native tables bind.
    let mut needs_payload = vec![false; scene.textures.len()];
    for cm in super::scene::mat_cutout(scene) {
        if cm != 0 {
            needs_payload[(cm - 1) as usize] = true;
        }
    }
    for [t1, _] in super::scene::mat_height(scene) {
        if t1 != 0 {
            needs_payload[(t1 - 1) as usize] = true;
        }
    }

    let mut by_key: BTreeMap<(u32, u32, u32, bool), Vec<u32>> = BTreeMap::new();
    for (i, t) in scene.textures.iter().enumerate() {
        let levels = 1 + t.mips.len() as u32;
        by_key.entry((t.w, t.h, levels, t.srgb)).or_default().push(i as u32);
    }

    let mut p = WebTexPlan {
        meta: vec![MetaRow { w: 0, h: 0, bl: 0, ofs: NO_PAYLOAD }; scene.textures.len()],
        ..Default::default()
    };
    for ((w, h, levels, srgb), layers) in by_key {
        let b = p.buckets.len() as u32;
        for (layer, &ti) in layers.iter().enumerate() {
            p.meta[ti as usize] =
                MetaRow { w, h, bl: (b << 16) | layer as u32, ofs: NO_PAYLOAD };
        }
        p.buckets.push(Bucket { w, h, levels, srgb, layers });
    }
    for (i, t) in scene.textures.iter().enumerate() {
        if !needs_payload[i] {
            continue;
        }
        p.meta[i].ofs = p.texels.len() as u32;
        p.texels.extend(t.texels.iter().map(|&[r, g, b, a]| {
            u32::from(r) | u32::from(g) << 8 | u32::from(b) << 16 | u32::from(a) << 24
        }));
    }
    p
}

/// The generated HLSL block: `#define WEB_TEX 1`, the declarations, and the
/// three dispatch helpers the choke points call. Compiles for ANY bucket
/// count including zero (an untextured scene's switch is just its default,
/// and the meta/texel buffers bind as dummies).
pub fn hlsl(p: &WebTexPlan) -> String {
    use std::fmt::Write as _;
    let mut s = String::with_capacity(2048 + p.buckets.len() * 160);
    let _ = write!(
        s,
        "#define WEB_TEX 1\n\
         // GENERATED by gfx::texweb (the browser texture plan) — do not edit.\n\
         struct WebTexMeta {{ uint w; uint h; uint bl; uint ofs; }};\n\
         StructuredBuffer<WebTexMeta> web_tex_meta : register(t{META_REG}, space1);\n\
         StructuredBuffer<uint>       web_texels   : register(t{TEXELS_REG}, space1);\n",
    );
    for i in 0..p.buckets.len() {
        let _ = writeln!(
            s,
            "Texture2DArray<float4> web_bucket_{i} : register(t{}, space1);",
            BUCKET_REG0 as usize + i
        );
    }
    s.push_str(
        "uint2 web_tex_dims(uint ti) {\n\
         \x20   WebTexMeta m = web_tex_meta[ti];\n\
         \x20   return uint2(m.w, m.h);\n\
         }\n\
         uint web_tex_a8(uint ti, uint x, uint y) {\n\
         \x20   WebTexMeta m = web_tex_meta[ti];\n\
         \x20   return web_texels[m.ofs + y * m.w + x] >> 24u;\n\
         }\n",
    );
    for (name, args, call) in [
        ("web_tex_grad", "float2 gu, float2 gv", "SampleGrad(s, c, gu, gv)"),
        ("web_tex_level", "float lod", "SampleLevel(s, c, lod)"),
    ] {
        let _ = writeln!(s, "float4 {name}(SamplerState s, uint ti, float2 uv, {args}) {{");
        s.push_str(
            "    uint bl = web_tex_meta[ti].bl;\n\
             \x20   float3 c = float3(uv.x, uv.y, float(bl & 0xffffu));\n\
             \x20   switch (bl >> 16u) {\n",
        );
        for i in 0..p.buckets.len() {
            let _ = writeln!(s, "    case {i}u: return web_bucket_{i}.{call};");
        }
        s.push_str("    default: return float4(0.5, 0.5, 0.5, 1.0);\n    }\n}\n");
    }
    s
}

/// Teeth for the plan and the codegen (wired into `--check`): grouping,
/// remap injectivity, payload byte layout, and the generated block's shape.
pub fn self_test() -> Result<(), String> {
    use crate::texture::Texture;
    let tex = |w: u32, h: u32, srgb: bool, alpha: u8| Texture {
        w,
        h,
        texels: (0..w * h).map(|i| [i as u8, 1, 2, alpha]).collect(),
        alpha_masked: alpha < 250,
        srgb,
        source: String::new(),
        h2n: false,
        n2h: false,
        normal_role: false,
        mips: Vec::new(),
        var_mips: Vec::new(),
    };
    let mut scene = crate::scene::procedural_scene();
    if !scene.textures.is_empty() {
        return Err("texweb: the procedural scene grew textures — retune this test".into());
    }
    // Four textures: two share a bucket key, one differs by srgb, one by
    // size; texture 1 is a cutout consumer (payload), the rest are not.
    scene.textures = vec![tex(8, 8, true, 255), tex(8, 8, true, 0), tex(8, 8, false, 255), tex(4, 4, true, 255)];
    scene.materials[0].kind = crate::scene::MatKind::Textured { tex: 1 };
    let p = plan(&scene);
    if p.buckets.len() != 3 {
        return Err(format!("texweb: want 3 buckets, got {}", p.buckets.len()));
    }
    // BTreeMap order: (4,4,1,true) < (8,8,1,false) < (8,8,1,true).
    if p.buckets[0].layers != [3] || p.buckets[1].layers != [2] || p.buckets[2].layers != [0, 1] {
        return Err(format!("texweb: bucket layout wrong: {:?}", p.buckets));
    }
    if p.meta[0].bl != (2 << 16) || p.meta[1].bl != (2 << 16 | 1) {
        return Err("texweb: shared-bucket remap wrong".into());
    }
    // Payload: exactly texture 1's 64 words, alpha byte on top.
    if p.meta[1].ofs != 0 || p.texels.len() != 64 {
        return Err(format!(
            "texweb: payload wrong (ofs {}, {} words — want 0, 64)",
            p.meta[1].ofs,
            p.texels.len()
        ));
    }
    if p.meta[0].ofs != NO_PAYLOAD || p.meta[2].ofs != NO_PAYLOAD {
        return Err("texweb: payload leaked onto a non-Load texture".into());
    }
    if p.texels[5] != (5u32 | 1 << 8 | 2 << 16) {
        return Err("texweb: RGBA8 word packing wrong (want r|g<<8|b<<16|a<<24)".into());
    }
    let code = hlsl(&p);
    for want in [
        "#define WEB_TEX 1",
        // The literal registers pin META_REG/TEXELS_REG/BUCKET_REG0 — the
        // native root-signature range and the wgpu layouts read those consts,
        // so a drifted const would silently rebind every consumer.
        "web_tex_meta : register(t10, space1)",
        "web_texels   : register(t11, space1)",
        "web_bucket_2 : register(t14, space1)",
        "case 2u: return web_bucket_2.SampleGrad(s, c, gu, gv);",
        "case 2u: return web_bucket_2.SampleLevel(s, c, lod);",
    ] {
        if !code.contains(want) {
            return Err(format!("texweb: generated block lacks `{want}`"));
        }
    }
    // Anti-vacuity for the zero-texture arm: the block must still compile-
    // shape correctly (no bucket decls, a default-only switch).
    scene.textures.clear();
    scene.materials[0].kind = crate::scene::MatKind::Diffuse;
    let empty = hlsl(&plan(&scene));
    if empty.contains("web_bucket_0") || !empty.contains("default: return float4(0.5") {
        return Err("texweb: zero-texture block malformed".into());
    }
    Ok(())
}
